baseURL = "https://lsampras.github.io/"
languageCode = "en-us"
title = "Sampras Lopes"
theme = "archie"
publishDir = "docs"


[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = ""


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lsampras"
text = "Github"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:lsampras@protonmail.com"
text = "Email"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2
